### ISSUE TITLE
Windex: User can grant himself admin/enabled rights

### ISSUE THREAD

**Issue by j-bernard** [CIRALabs/shg_mud_supervisor#9]

**Comment by mcr** [comment]
I am unable to reproduce this.  The code will return HTTP-200 (OK) if you attempt to POST to protected fields, but it will not update the database.  See new test case f73f491 and can you please let me know if you did something different?

**Comment by mcr** [comment]
https://code.credil.org/issues/15162 issue, and ticket closed.
